name: Run Trivy Container Scan Action
description: Run container scanning using Trivy (optional build for PR)

inputs:      
  container-ref:
    description: 'Locally built container id which Trivy should scan'
    required: true
    type: string
  severity:
    description: 'Severities of vulnerabilities to be scanned for and displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false  
    default: 'CRITICAL,HIGH'
    type: string
  limit-severities-for-sarif:
    description: 'By default SARIF format enforces output of all vulnerabilities regardless of configured severities. To override this behavior set this parameter to true'
    required: false  
    default: true
    type: boolean 
  upload-to-github-security-tab:
    description: 'Upload results to GitHub security tab?'
    required: false
    default: false
    type: boolean
  ignore-unfixed:
    description: 'Ignore unpatched/unfixed vulnerabilities'
    required: false
    default: false
    type: boolean 
  skip-dirs:
    description: 'Comma separated list of directories where traversal is skipped'
    required: false 
    default: ''
    type: string
  skip-files:
    description: 'Comma separated list of files where traversal is skipped'
    required: false  
    default: ''
    type: string
  timeout:
    description: 'Scan timeout duration'
    required: false  
    default: '10m0s'
    type: string
  exit-code:
    description: 'Exit code when specified vulnerabilities are found (0).'
    required: false  
    default: '0'
    type: string
  trivyignores:
    description: 'Comma-separated list of relative paths in repository to one or more .trivyignore files, for usage see https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/examples/filter/'
    required: false         
    type: string

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability scanner
      if: ${{ inputs.upload-to-github-security-tab != 'true' }}
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.container-ref }}'
        format: 'table'        
        exit-code: '${{ inputs.exit-code }}'
        ignore-unfixed: ${{inputs.ignore-unfixed}}
        vuln-type: 'os,library'
        severity: ${{inputs.severity}}
        timeout: ${{inputs.timeout}}
        trivyignores: ${{inputs.trivyignores}}

    # Runs scanner for printing to GitHub Security Tab
    - name: Run Trivy vulnerability scanner for printing to GitHub Security Tab
      if: ${{ inputs.upload-to-github-security-tab == 'true' }}
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.container-ref }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '${{ inputs.exit-code }}'
        ignore-unfixed: ${{inputs.ignore-unfixed}}
        vuln-type: 'os,library'
        severity: ${{inputs.severity}}
        timeout: ${{inputs.timeout}}
        trivyignores: ${{inputs.trivyignores}}
        limit-severities-for-sarif: ${{inputs.limit-severities-for-sarif}}

    - name: Upload Trivy scan results to GitHub Security tab
      if: ${{ inputs.upload-to-github-security-tab == 'true' && always() }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'