# This is a sample template for calling a reusable workflow from NEDSS-Workflows public repository (Trivy-container-scan.yaml)
# The workflow can be used in either an push or pull-request depending on use-case. 
#
# NOTE: Set paths in order to restrict the workflow to run only when specific files are changed
#
# Manual variable edits. For a full list of accepted variables see the README.md
# Edit:
# 1. <microservice_name> 
# 2. <dockerfile_relative_path> to correctly identify your microservice and dockerfile path

name: Test Trivy
on:
  pull_request:
    branches:
      - 'main'
 
jobs:
  call-run-container-scan:
    uses: CDCgov/NEDSS-Workflows/.github/workflows/Trivy-container-scan.yaml@main
    with:
      microservice_name: <microservice_name>
      dockerfile_relative_path: <dockerfile_relative_path>
      