# THROWAWAY — delete before merging DEV-389 to main
name: TEST DEV-389 provenance
on:
  workflow_dispatch:

jobs:
  test-other:
    permissions:
      id-token: write
      contents: read
      security-events: write
    uses: ./.github/workflows/Build-other-microservice-container.yaml
    with:
      microservice_name: dev-389-provenance-test
      dockerfile_relative_path: ./sample_templates/dev-389-test
      environment_classifier: SNAPSHOT
    secrets: inherit