### Pulls docker images from private ECR and publishes them to public Quay.io

name: Moving Docker images from ECR to Quay.io

on:
  workflow_dispatch:
    inputs:
      ecr-image-repo:
        description: 'ECR image repo name to pull'
        type: string
        required: true 
      ecr-image-tag:
        description: 'ECR image tag to pull'
        type: string
        required: true
      quay-image-repo:
        description: 'Quay.io image repo name'
        type: string
        required: true
      quay-image-tag:
        description: 'Quay.io image tag (could be same as in ECR)'
        type: string
        required: true
  workflow_call:
    inputs:
      ecr-image-repo:
        description: 'ECR image repo name to pull'
        type: string
        required: true 
      ecr-image-tag:
        description: 'ECR image tag to pull'
        type: string
        required: true
      quay-image-repo:
        description: 'Quay.io image repo name'
        type: string
        required: true
      quay-image-tag:
        description: 'Quay.io image tag (could be same as in ECR)'
        type: string
        required: true

permissions:
  id-token: write
  contents: read

env:
  ACCOUNT_ID: ${{secrets.CDC_NBS_SANDBOX_SHARED_SERVICES_ACCOUNTID}}
  REGION: ${{secrets.AWS_REGION}}
  GITHUB_REPO_NAME: "NEDSS-Workflows"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.ACCOUNT_ID}}:role/cdc-github-${{env.GITHUB_REPO_NAME}}-dev-role
          aws-region: ${{env.REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from ECR
        run: docker pull ${{ env.ACCOUNT_ID }}.dkr.ecr.${{env.REGION}}.amazonaws.com/${{inputs.ecr-image-repo}}:${{ inputs.ecr-image-tag }}

      - name: Login to Quay.io with Robot Account
        run: docker login -u=${{secrets.QUAY_ROBOT_USERNAME}} -p=${{secrets.QUAY_ROBOT_TOKEN}} quay.io

      - name: Tag image for Quay.io
        run: docker tag ${{env.ACCOUNT_ID}}.dkr.ecr.${{env.REGION}}.amazonaws.com/${{inputs.ecr-image-repo}}:${{inputs.ecr-image-tag}} quay.io/${{secrets.QUAY_ORGANIZATION}}/${{inputs.quay-image-repo}}:${{inputs.quay-image-tag}}

      - name: Push image to Quay.io
        run: docker push quay.io/${{secrets.QUAY_ORGANIZATION}}/${{inputs.quay-image-repo}}:${{ inputs.quay-image-tag }}

