name: Moving All NBS7 Docker images from ECR to Quay.io

on:
# workflow_dispatch:
#     inputs:
#       nifi-publish-new-container: 
#         description: Publish New NiFi container?
#         type: boolean        
#         default: false
#         required: true
#       nifi-ecr-tag: 
#         description: NiFi tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       nifi-quay-tag: 
#         description: NiFi release tag for public quay.io.
#         type: string        
#         required: false
#       elasticsearch-publish-new-container: 
#         description: Publish New lasticSearch container?
#         type: boolean        
#         default: false
#         required: true
#       elasticsearch-ecr-tag: 
#         description: ElasticSearch tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       elasticsearch-quay-tag: 
#         description: ElasticSearch release tag for public quay.io.
#         type: string        
#         required: false
#       mapi-publish-new-container: 
#         description: Publish New Modernization API container?
#         type: boolean        
#         default: false
#         required: true
#       mapi-ecr-tag: 
#         description: Modernization API tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       mapi-quay-tag: 
#         description: Modernization API release tag for public quay.io.
#         type: string        
#         required: false
#       pbapi-publish-new-container: 
#         description: Publish New Page Builder API container?
#         type: boolean        
#         default: false
#         required: true
#       pbapi-ecr-tag: 
#         description: Page Builder API tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       pbapi-quay-tag: 
#         description: Page Builder API release tag for public quay.io.
#         type: string        
#         required: false
#       ngateway-publish-new-container: 
#         description: Publish New NBS Gateway container?
#         type: boolean        
#         default: false
#         required: true
#       ngateway-ecr-tag: 
#         description: NBS Gateway tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       ngateway-quay-tag: 
#         description: NBS Gateway release tag for public quay.io.
#         type: string        
#         required: false
#       diservice-publish-new-container: 
#         description: Publish New DI Service container?
#         type: boolean        
#         default: false
#         required: true
#       diservice-ecr-tag: 
#         description: DI Service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       diservice-quay-tag: 
#         description: DI Service release tag for public quay.io.
#         type: string        
#         required: false
#       nnd-data-publish-new-container: 
#         description: Publish New nnd-data-exchange-service container?
#         type: boolean        
#         default: false
#         required: true
#       nnd-data-ecr-tag: 
#         description: nnd-data-exchange-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       nnd-data-quay-tag: 
#         description: nnd-data-exchange-service release tag for public quay.io.
#         type: string        
#         required: false
#       investigation-reporting-publish-new-container: 
#         description: Publish New investigation-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#      investigation-reporting-ecr-tag: 
#         description: investigation-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       investigation-reporting-quay-tag: 
#         description: investigation-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       ldfdata-publish-new-container: 
#         description: Publish New ldfdata-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#       ldfdata-data-ecr-tag: 
#         description: ldfdata-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       ldfdata-data-quay-tag: 
#         description: ldfdata-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       observation-reporting-publish-new-container: 
#         description: Publish New observation-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#       observation-reporting-ecr-tag: 
#         description: observation-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       observation-reporting-quay-tag: 
#         description: observation-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       organization-reporting-publish-new-container: 
#         description: Publish New organization-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#       organization-reporting-ecr-tag: 
#         description: organization-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       organization-reporting-quay-tag: 
#         description: organization-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       person-reporting-publish-new-container: 
#         description: Publish New person-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#       person-reporting-ecr-tag: 
#         description: person-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       person-reporting-quay-tag: 
#         description: person-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       post-processing-publish-new-container: 
#         description: Publish New post-processing-reporting-service container?
#         type: boolean        
#         default: false
#         required: true
#       post-processing-ecr-tag: 
#         description: post-processing-reporting-service tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       post-processing-quay-tag: 
#         description: post-processing-reporting-service release tag for public quay.io.
#         type: string        
#         required: false
#       liquibase-publish-new-container: 
#         description: Publish New liquibase container?
#         type: boolean        
#         default: false
#         required: true
#       liquibase-ecr-tag: 
#         description: liquibase tag from AWS private ECR (image that is uploaded to quay.io).
#         type: string        
#         required: false
#       liquibase-quay-tag: 
#         description: liquibase-reporting-service release tag for public quay.io.
#         type: string        
#         required: false

jobs:
  publish-nifi:
    name: Publish Container CDCgov/NEDSS-Modernization for nifi microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/nifi
      nifi-ecr-tag: ${{inputs.nifi-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/nifi
      nifi-quay-tag: ${{inputs.nifi-quay-tag}}
  
  publish-elasticsearch:
    name: Publish Container CDCgov/NEDSS-Modernization for elasticsearch microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/elasticsearch
      elasticsearch-ecr-tag: ${{inputs.elasticsearch-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/elasticsearch
      elasticsearch-quay-tag: ${{inputs.elasticsearch-quay-tag}}

  publish-modernization-api:
    name: Publish Container CDCgov/NEDSS-Modernization for modernization-api microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/modernization-api
      mapi-ecr-tag: ${{inputs.mapi-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/modernization-api
      mapi-quay-tag: ${{inputs.mapi-quay-tag}}      

  publish-page-builder-api:
    name: Publish Container CDCgov/NEDSS-Modernization for page-builder-ap microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/page-builder-api
      pbapi-ecr-tag: ${{inputs.pbapi-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/page-builder-api
      pbapi-quay-tag: ${{inputs.pbapi-quay-tag}}      

  publish-nbs-gateway:
    name: Publish Container CDCgov/NEDSS-Modernization for nbs-gateway microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/nbs-gateway
      ngateway-ecr-tag: ${{inputs.ngateway-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/nbs-gateway
      ngateway-quay-tag: ${{inputs.ngateway-quay-tag}}

  publish-data-ingestion-service:
    name: Publish Container CDCgov/NEDSS-DataIngestion for data-ingestion-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-ingestion-service
      diservice-ecr-tag: ${{inputs.diservice-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-ingestion-service
      diservice-quay-tag: ${{inputs.diservice-quay-tag}}
 
  publish-nnd-data-exchange-service:
    name: Publish Container CDCgov/NEDSS-NNDSS for nnd-data-exchange-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/nnd-data-exchange-service
      nnd-data-ecr-tag: ${{inputs.nnd-data-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/nnd-data-exchange-service
      nnd-data-quay-tag: ${{inputs.nnd-data-quay-tag}}

  publish-investigation-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for investigation-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-reporting-service/investigation-reporting-service
      investigation-reporting-ecr-tag: ${{inputs.investigation-reporting-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-reporting-service/investigation-reporting-service
      investigation-reporting-quay-tag: ${{inputs.investigation-reporting-quay-tag}}

  publish-ldfdata-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for ldfdata-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-reporting-service/ldfdata-reporting-service
      ldfdata-data-ecr-tag: ${{inputs.ldfdata-data-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-reporting-service/ldfdata-reporting-service
      ldfdata-data-quay-tag: ${{inputs.ldfdata-data-quay-tag}}

  publish-observation-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for observation-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/
      observation-reporting-ecr-tag: ${{inputs.observation-reporting-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/
      observation-reporting-quay-tag: ${{inputs.observation-reporting-quay-tag}}
      
  publish-organization-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for organization-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-reporting-service/organization-reporting-service
      organization-reporting-ecr-tag: ${{inputs.organization-reporting-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-reporting-service/organization-reporting-service
      organization-reporting-quay-tag: ${{inputs.organization-reporting-quay-tag}}
      
  publish-person-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for person-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-reporting-service/person-reporting-service
      person-reporting-ecr-tag: ${{inputs.person-reporting-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-reporting-service/person-reporting-service
      person-reporting-quay-tag: ${{inputs.person-reporting-quay-tag}}
      
  publish-post-processing-reporting-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for post-processing-reporting-service microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/data-reporting-service/post-processing-reporting-service
      post-processing-ecr-tag: ${{inputs.post-processing-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/data-reporting-service/post-processing-reporting-service
      post-processing-quay-tag: ${{inputs.post-processing-quay-tag}}   

  publish-liquibase-service:
    name: Publish Container CDCgov/NEDSS-DataReporting for liquibase microservice 
    uses: ./.github/workflows/ecr-quay.io-image-transfer.yml
    secrets: inherit
    with:        
      ecr-image-repo: cdc-nbs-modernization/liquibase-service
      liquibase-ecr-tag: ${{inputs.liquibase-ecr-tag-ecr-tag}}
      quay-image-repo: us-cdcgov/cdc-nbs-modernization/liquibase-service
      liquibase-quay-tag: ${{inputs.liquibase-quay-tag}}     