name: Test Helm Chart Update

on:
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  test-call:
    uses: ./.github/workflows/Update-helm-charts.yaml
    with:
      values_file_with_path: "charts/rtr/values-dummy.yaml"
      new_image_tag: "1.0.1-SNAPSHOT.2d80af1"
      microservice_name: "investigation-reporting"
    secrets:
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      HELM_TOKEN: ${{ secrets.HELM_TOKEN }}
